id: IB0DAF2E6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:54:42+00:00'
last_modified: '2022-06-08T13:24:01.502998+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03597
  title: ཀན་ལྷོའི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་རིགས།༡༣
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0387:
      image_group_id: I00KG03614
      title: 'Volume 1 of 1949-1999 kan lho''i lo rgyus dpyad gzhi''i yig rigs : 13'
      total_pages: 135
      order: 1
      base_file: 0387.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
