id: P007030
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03597
  title: ཀན་ལྷོའི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་རིགས།༡༣
  author: ''
  volumes:
    7a89744e5510417e9b61f2f2304fdb9d:
      image_group_id: I00KG03614
      title: ''
      volume_number: 1
      total_pages: 135
ebook_metadata:
  title: ཀན་ལྷོའི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་རིགས།༡༣
  author: ''
  sku: P007030
  cover: cover.jpg
  layers:
  - pagination
