id: P007030
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:37:18.708887
source_metadata:
  id: bdr:W00KG03597
  title: ཀན་ལྷོའི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་རིགས།༡༣
  author: ''
  volumes:
    1908e564ccbe4df3b075715d29dbde43:
      image_group_id: I00KG03614
      title: 'Volume 1 of 1949-1999 kan lho''i lo rgyus dpyad gzhi''i yig rigs : 13'
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
